import type { Recipe } from '@/types'

// Données mock partagées pour les recettes
export const mockRecipes: Record<string, Recipe> = {
  '1': {
    id: '1',
    title: 'Buddha Bowl Quinoa aux légumes grillés',
    description: 'Un bol équilibré et coloré avec des saveurs méditerranéennes. Parfait pour un déjeuner sain et rassasiant.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    servings: 2,
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Quinoa', quantity: 150, unit: 'g' },
      { id: '2', name: 'Pois chiches', quantity: 200, unit: 'g', preparation: 'rincés et égouttés' },
      { id: '3', name: 'Concombre', quantity: 1, unit: 'pièce', preparation: 'coupé en dés' },
      { id: '4', name: 'Tomates cerises', quantity: 150, unit: 'g', preparation: 'coupées en deux' },
      { id: '5', name: 'Avocat', quantity: 1, unit: 'pièce', preparation: 'tranché' },
      { id: '6', name: 'Feta', quantity: 100, unit: 'g', preparation: 'émiettée' },
      { id: '7', name: 'Olives Kalamata', quantity: 50, unit: 'g' },
      { id: '8', name: 'Huile d\'olive', quantity: 2, unit: 'c. à soupe' },
      { id: '9', name: 'Jus de citron', quantity: 1, unit: 'c. à soupe' },
      { id: '10', name: 'Houmous', quantity: 4, unit: 'c. à soupe' },
    ],
    instructions: [
      'Rincez le quinoa et faites-le cuire selon les instructions du paquet. Laissez refroidir.',
      'Pendant ce temps, faites rôtir les pois chiches avec un filet d\'huile d\'olive au four à 200°C pendant 15-20 minutes.',
      'Préparez tous les légumes : coupez le concombre en dés, les tomates cerises en deux, et tranchez l\'avocat.',
      'Préparez la vinaigrette en mélangeant l\'huile d\'olive et le jus de citron.',
      'Assemblez le bowl : répartissez le quinoa tiède dans deux bols, disposez harmonieusement les légumes.',
      'Ajoutez une cuillère de houmous au centre et arrosez de vinaigrette.',
      'Servez immédiatement, garni d\'herbes fraîches si désiré.',
    ],
    nutritionPerServing: {
      calories: 450,
      proteins: 18,
      carbs: 48,
      fats: 22,
      fiber: 12,
    },
    tags: ['healthy', 'végétarien', 'méditerranéen', 'équilibré'],
    cuisineType: 'Méditerranéenne',
    dietTypes: ['vegetarian'],
    allergens: ['gluten', 'lait'],
    source: 'community',
    rating: 4.8,
    ratingCount: 124,
    isFavorite: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  '2': {
    id: '2',
    title: 'Saumon Teriyaki et riz basmati',
    description: 'Un classique de la cuisine japonaise, avec une sauce sucrée-salée irrésistible.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    servings: 4,
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: 'medium',
    ingredients: [
      { id: '1', name: 'Pavés de saumon', quantity: 600, unit: 'g' },
      { id: '2', name: 'Riz basmati', quantity: 300, unit: 'g' },
      { id: '3', name: 'Sauce soja', quantity: 60, unit: 'ml' },
      { id: '4', name: 'Miel', quantity: 2, unit: 'c. à soupe' },
      { id: '5', name: 'Vinaigre de riz', quantity: 1, unit: 'c. à soupe' },
      { id: '6', name: 'Ail', quantity: 2, unit: 'gousses', preparation: 'émincées' },
      { id: '7', name: 'Gingembre frais', quantity: 1, unit: 'c. à café', preparation: 'râpé' },
      { id: '8', name: 'Graines de sésame', quantity: 1, unit: 'c. à soupe' },
    ],
    instructions: [
      'Faites cuire le riz basmati selon les instructions du paquet.',
      'Mélangez la sauce soja, le miel, le vinaigre de riz, l\'ail et le gingembre dans un bol.',
      'Faites chauffer une poêle à feu moyen-vif.',
      'Faites cuire les pavés de saumon côté peau 4 minutes, retournez et cuisez 3 minutes.',
      'Versez la sauce teriyaki et laissez réduire 2-3 minutes.',
      'Parsemez de graines de sésame avant de servir.',
      'Servez sur un lit de riz basmati.',
    ],
    nutritionPerServing: {
      calories: 520,
      proteins: 35,
      carbs: 45,
      fats: 18,
    },
    tags: ['protéiné', 'omega-3', 'asiatique'],
    cuisineType: 'Japonaise',
    dietTypes: [],
    allergens: ['soja', 'sésame', 'poisson'],
    source: 'community',
    rating: 4.6,
    ratingCount: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  '3': {
    id: '3',
    title: 'Salade Méditerranéenne au feta',
    description: 'Une salade fraîche et légère aux saveurs de la Méditerranée.',
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    servings: 2,
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Laitue romaine', quantity: 200, unit: 'g' },
      { id: '2', name: 'Tomates', quantity: 2, unit: 'pièces', preparation: 'coupées en quartiers' },
      { id: '3', name: 'Concombre', quantity: 1, unit: 'pièce', preparation: 'en rondelles' },
      { id: '4', name: 'Oignon rouge', quantity: 0.5, unit: 'pièce', preparation: 'émincé' },
      { id: '5', name: 'Feta', quantity: 100, unit: 'g', preparation: 'émiettée' },
      { id: '6', name: 'Olives noires', quantity: 50, unit: 'g' },
      { id: '7', name: 'Huile d\'olive', quantity: 3, unit: 'c. à soupe' },
      { id: '8', name: 'Origan séché', quantity: 1, unit: 'c. à café' },
    ],
    instructions: [
      'Lavez et essorez la laitue, disposez-la dans un saladier.',
      'Ajoutez les tomates, concombre et oignon rouge.',
      'Répartissez la feta émiettée et les olives.',
      'Arrosez d\'huile d\'olive et saupoudrez d\'origan.',
      'Mélangez délicatement et servez frais.',
    ],
    nutritionPerServing: {
      calories: 320,
      proteins: 12,
      carbs: 15,
      fats: 24,
      fiber: 4,
    },
    tags: ['express', 'léger', 'végétarien'],
    cuisineType: 'Méditerranéenne',
    dietTypes: ['vegetarian'],
    allergens: ['lait'],
    source: 'community',
    rating: 4.5,
    ratingCount: 67,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  '4': {
    id: '4',
    title: 'Poulet grillé aux herbes de Provence',
    description: 'Un classique français, tendre et parfumé aux herbes.',
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800',
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Blancs de poulet', quantity: 800, unit: 'g' },
      { id: '2', name: 'Herbes de Provence', quantity: 2, unit: 'c. à soupe' },
      { id: '3', name: 'Ail', quantity: 4, unit: 'gousses', preparation: 'émincées' },
      { id: '4', name: 'Huile d\'olive', quantity: 3, unit: 'c. à soupe' },
      { id: '5', name: 'Jus de citron', quantity: 2, unit: 'c. à soupe' },
      { id: '6', name: 'Sel et poivre', quantity: 1, unit: 'pincée' },
    ],
    instructions: [
      'Mélangez l\'huile d\'olive, les herbes de Provence, l\'ail et le jus de citron.',
      'Badigeonnez les blancs de poulet avec cette marinade.',
      'Laissez mariner 30 minutes si possible.',
      'Faites griller le poulet à feu moyen-vif, 6-7 minutes de chaque côté.',
      'Laissez reposer 5 minutes avant de servir.',
      'Accompagnez de légumes grillés ou d\'une salade.',
    ],
    nutritionPerServing: {
      calories: 380,
      proteins: 42,
      carbs: 2,
      fats: 22,
    },
    tags: ['protéiné', 'classic', 'français'],
    cuisineType: 'Française',
    dietTypes: [],
    allergens: [],
    source: 'community',
    rating: 4.9,
    ratingCount: 156,
    isFavorite: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  '5': {
    id: '5',
    title: 'Curry de pois chiches et épinards',
    description: 'Un curry végétalien réconfortant et épicé.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    servings: 4,
    prepTime: 15,
    cookTime: 25,
    totalTime: 40,
    difficulty: 'medium',
    ingredients: [
      { id: '1', name: 'Pois chiches', quantity: 400, unit: 'g', preparation: 'égouttés' },
      { id: '2', name: 'Épinards frais', quantity: 300, unit: 'g' },
      { id: '3', name: 'Lait de coco', quantity: 400, unit: 'ml' },
      { id: '4', name: 'Pâte de curry', quantity: 2, unit: 'c. à soupe' },
      { id: '5', name: 'Oignon', quantity: 1, unit: 'pièce', preparation: 'émincé' },
      { id: '6', name: 'Ail', quantity: 3, unit: 'gousses', preparation: 'émincées' },
      { id: '7', name: 'Gingembre frais', quantity: 2, unit: 'cm', preparation: 'râpé' },
      { id: '8', name: 'Cumin', quantity: 1, unit: 'c. à café' },
    ],
    instructions: [
      'Faites revenir l\'oignon, l\'ail et le gingembre dans une grande poêle.',
      'Ajoutez la pâte de curry et le cumin, faites cuire 1 minute.',
      'Versez le lait de coco et portez à ébullition.',
      'Ajoutez les pois chiches et laissez mijoter 15 minutes.',
      'Incorporez les épinards et faites cuire 3-4 minutes.',
      'Servez avec du riz basmati ou du naan.',
    ],
    nutritionPerServing: {
      calories: 410,
      proteins: 15,
      carbs: 35,
      fats: 25,
      fiber: 10,
    },
    tags: ['végan', 'épicé', 'réconfortant'],
    cuisineType: 'Indienne',
    dietTypes: ['vegan', 'vegetarian'],
    allergens: [],
    source: 'community',
    rating: 4.4,
    ratingCount: 45,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  '6': {
    id: '6',
    title: 'Omelette aux champignons et fromage',
    description: 'Une omelette moelleuse et savoureuse, prête en 10 minutes.',
    imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800',
    servings: 1,
    prepTime: 5,
    cookTime: 5,
    totalTime: 10,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Œufs', quantity: 3, unit: 'pièces' },
      { id: '2', name: 'Champignons', quantity: 100, unit: 'g', preparation: 'émincés' },
      { id: '3', name: 'Gruyère râpé', quantity: 40, unit: 'g' },
      { id: '4', name: 'Beurre', quantity: 15, unit: 'g' },
      { id: '5', name: 'Ciboulette', quantity: 1, unit: 'c. à soupe', preparation: 'ciselée' },
      { id: '6', name: 'Sel et poivre', quantity: 1, unit: 'pincée' },
    ],
    instructions: [
      'Battez les œufs avec sel et poivre.',
      'Faites revenir les champignons dans le beurre 3 minutes.',
      'Versez les œufs battus sur les champignons.',
      'Laissez cuire à feu doux, en remuant délicatement.',
      'Quand l\'omelette est presque prise, ajoutez le gruyère.',
      'Pliez l\'omelette et servez avec la ciboulette.',
    ],
    nutritionPerServing: {
      calories: 290,
      proteins: 22,
      carbs: 3,
      fats: 21,
    },
    tags: ['express', 'keto', 'végétarien'],
    cuisineType: 'Française',
    dietTypes: ['vegetarian', 'keto'],
    allergens: ['œufs', 'lait'],
    source: 'community',
    rating: 4.3,
    ratingCount: 78,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
}

// Liste simplifiée pour l'affichage dans la liste des recettes
export const mockRecipesList = Object.values(mockRecipes).map(recipe => ({
  id: recipe.id,
  title: recipe.title,
  imageUrl: recipe.imageUrl,
  calories: recipe.nutritionPerServing.calories,
  proteins: recipe.nutritionPerServing.proteins,
  prepTime: recipe.totalTime,
  difficulty: recipe.difficulty,
  rating: recipe.rating,
  ratingCount: recipe.ratingCount,
  tags: recipe.tags.map(t => t.charAt(0).toUpperCase() + t.slice(1)),
  isFavorite: recipe.isFavorite || false,
}))

// Fonction pour obtenir une recette par son ID
export function getRecipeById(id: string): Recipe | undefined {
  return mockRecipes[id]
}
