// Dashboard Components
export { default as CaloriesWidget } from './CaloriesWidget'
export { default as MacrosWidget } from './MacrosWidget'
export { default as QuickActionsWidget } from './QuickActionsWidget'
export { GamificationPanel } from './GamificationPanel'
export { WellnessWidget } from './WellnessWidget'
export { SportWidget } from './SportWidget'
export { LymIA } from './LymIA'
export { LymIAWidget } from './LymIAWidget'
export { CaloricBalance } from './CaloricBalance'
export { HydrationWidget } from './HydrationWidget'
export { MetabolicBoostWidget } from './MetabolicBoostWidget'
export { SportInitiationWidget } from './SportInitiationWidget'
export { ProgramsSection } from './ProgramsSection'
export { CoachInsights } from './CoachInsights'
export { RankingWidget } from './RankingWidget'
