// Dashboard Components
export { default as CaloriesWidget } from './CaloriesWidget'
export { default as MacrosWidget } from './MacrosWidget'
export { default as QuickActionsWidget } from './QuickActionsWidget'
export { GamificationPanel } from './GamificationPanel'
export { WellnessWidget } from './WellnessWidget'
export { SportWidget } from './SportWidget'
export { LymIA } from './LymIA'
export { CaloricBalance } from './CaloricBalance'
export { HydrationWidget } from './HydrationWidget'
export { MetabolicBoostWidget } from './MetabolicBoostWidget'
export { ProgramsSection } from './ProgramsSection'
export { ProgramsWidget } from './ProgramsWidget'
export { default as UnifiedCoachBubble } from './UnifiedCoachBubble'
export { RankingWidget } from './RankingWidget'
export { ProgressWidget } from './ProgressWidget'
