// Sport & Activity Types for PRESENCE Nutrition App
// LymIA Sport Program - Focus on real workouts, no NEAT tracking

// Session types
export type SessionType = 'walking' | 'resistance' | 'cardio' | 'recovery' | 'stretching' | 'hiit'

// Exercise intensity
export type ExerciseIntensity = 'low' | 'moderate' | 'high'

// Session difficulty perception
export type PerceivedDifficulty = 'too_easy' | 'just_right' | 'challenging' | 'too_hard'

// Energy level after session
export type EnergyAfterSession = 'exhausted' | 'tired' | 'good' | 'energized'

// Muscle groups
export type MuscleGroup =
  | 'full_body'
  | 'upper_body'
  | 'lower_body'
  | 'core'
  | 'chest'
  | 'back'
  | 'shoulders'
  | 'arms'
  | 'legs'
  | 'glutes'

// Equipment types
export type Equipment =
  | 'none'
  | 'dumbbells'
  | 'resistance_bands'
  | 'kettlebell'
  | 'pull_up_bar'
  | 'yoga_mat'
  | 'jump_rope'
  | 'foam_roller'

// Exercise definition
export interface Exercise {
  id: string
  name: string
  description: string
  duration?: number // seconds
  reps?: number
  sets?: number
  restBetweenSets?: number // seconds
  intensity: ExerciseIntensity
  muscleGroups: MuscleGroup[]
  equipment: Equipment[]
  alternatives?: string[] // Alternative exercise IDs
  videoUrl?: string
  imageUrl?: string
  tips?: string[]
}

// Generated session by AI
export interface GeneratedSession {
  id: string
  weekNumber: number
  dayOfWeek: number // 0-6 (Sunday-Saturday)
  type: SessionType
  title: string // "Marche énergisante", "Renforcement doux"
  description: string
  duration: number // minutes
  estimatedCalories?: number
  exercises: Exercise[]
  warmup?: Exercise[]
  cooldown?: Exercise[]
  aiReasoning?: string // Why this session was generated
  isCompleted: boolean
  completedAt?: string
  feedback?: SessionFeedback
}

// Session feedback from user
export interface SessionFeedback {
  sessionId: string
  date: string
  // Overall feeling
  overallFeeling: 1 | 2 | 3 | 4 | 5 // 1=😫 2=😕 3=😐 4=🙂 5=😄
  // Perceived difficulty
  perceivedDifficulty: PerceivedDifficulty
  // Energy after
  energyAfter: EnergyAfterSession
  // Exercises feedback
  likedExercises: string[] // Exercise IDs
  dislikedExercises: string[] // Exercise IDs
  // Pain or discomfort
  painOrDiscomfort?: string
  // Actual duration vs planned
  actualDuration: number // minutes
  // Free comment
  comment?: string
}

// Weekly program
export interface WeeklyProgram {
  id: string
  weekNumber: number
  startDate: string
  endDate: string
  sessions: GeneratedSession[]
  weeklyGoals: {
    activeMinutes: number
    resistanceSessions: number
    cardioSessions: number
    restDays: number
  }
  motivationalMessage: string // Generated by AI
  adaptations?: string[] // Changes from previous week
  isCompleted: boolean
  completionRate?: number // 0-100%
}

// AI program generation context
export interface ProgramGenerationContext {
  // User profile
  metabolismProfile: 'standard' | 'adaptive'
  age: number
  weight: number
  height: number
  gender: 'male' | 'female' | 'other'
  fitnessLevel: 'beginner' | 'intermediate' | 'advanced'
  goal: 'weight_loss' | 'muscle_gain' | 'maintenance' | 'health' | 'energy'

  // Current program state
  currentPhase: 'discovery' | 'walking_program' | 'resistance_intro' | 'full_program'
  weekInPhase: number
  completedWeeks: number

  // Historical data
  recentFeedbacks: SessionFeedback[]
  weightHistory: { date: string; weight: number }[]
  completedSessions: number
  missedSessions: number

  // User preferences
  availableEquipment: Equipment[]
  preferredSessionDuration: number // minutes
  availableDaysPerWeek: number[]
  dislikedExercises: string[]
  likedExercises: string[]
  injuries?: string[]
}

// AI adaptation triggers
export interface AdaptationTrigger {
  type:
    | 'difficulty_too_easy'
    | 'difficulty_too_hard'
    | 'weight_plateau'
    | 'exercise_disliked'
    | 'pain_reported'
    | 'missed_sessions'
    | 'phase_completed'
    | 'motivation_low'
  count: number
  threshold: number
  action: string
}

// Sport program store state
export interface SportProgramState {
  // Current state
  currentProgram: WeeklyProgram | null
  pastPrograms: WeeklyProgram[]
  currentSession: GeneratedSession | null

  // Stats
  totalSessionsCompleted: number
  currentStreak: number
  longestStreak: number
  averageSessionDuration: number

  // Preferences (learned from feedback)
  preferredExercises: string[]
  avoidedExercises: string[]

  // Loading states
  isGenerating: boolean
  error: string | null
}

// Phase progression criteria for LymIA Sport Program
export interface PhaseProgression {
  phase: 'discovery' | 'walking_program' | 'resistance_intro' | 'full_program'
  minimumWeeks: number
  criteria: {
    minCompletionRate: number // %
    minAverageFeeling: number // 1-5
    noPainReported: boolean
  }
  nextPhase: 'walking_program' | 'resistance_intro' | 'full_program' | null
}

export const PHASE_PROGRESSIONS: PhaseProgression[] = [
  {
    phase: 'discovery',
    minimumWeeks: 2,
    criteria: { minCompletionRate: 70, minAverageFeeling: 3, noPainReported: true },
    nextPhase: 'walking_program',
  },
  {
    phase: 'walking_program',
    minimumWeeks: 3,
    criteria: { minCompletionRate: 75, minAverageFeeling: 3.5, noPainReported: true },
    nextPhase: 'resistance_intro',
  },
  {
    phase: 'resistance_intro',
    minimumWeeks: 4,
    criteria: { minCompletionRate: 80, minAverageFeeling: 3.5, noPainReported: true },
    nextPhase: 'full_program',
  },
  {
    phase: 'full_program',
    minimumWeeks: 0, // Ongoing
    criteria: { minCompletionRate: 0, minAverageFeeling: 0, noPainReported: false },
    nextPhase: null,
  },
]
