// Onboarding Components
export { OnboardingLayout } from './OnboardingLayout'
export { OnboardingHero } from './OnboardingHero'
export { OnboardingBenefits } from './OnboardingBenefits'
export { StepWelcome } from './StepWelcome'
export { StepBasicInfo } from './StepBasicInfo'
export { StepGoal } from './StepGoal'
export { StepActivity } from './StepActivity'
export { StepDiet } from './StepDiet'
export { StepCooking } from './StepCooking'
export { StepLifestyle } from './StepLifestyle'
export { StepMetabolism } from './StepMetabolism'
export { StepSportInitiation } from './StepSportInitiation'
export { StepMetabolicProgram } from './StepMetabolicProgram'
export { StepWellnessProgram } from './StepWellnessProgram'
export { StepAnalysis } from './StepAnalysis'

// Progressive Unlock Components
export { default as FeatureDiscoveryModal } from './FeatureDiscoveryModal'
export { default as FeatureLockOverlay } from './FeatureLockOverlay'
